### ISSUE TITLE
Preview オプションの追加

### ISSUE THREAD

**Issue by Mahito** [x-motemen/blogsync#103]
2023年10月16日 `app:control/app:preview` 要素 が増えたようです。

>app:control/app:preview要素 
>ブログエントリが下書きのとき下書きプレビューの共有URLを発行するか指定できます。"yes"を指定すると共有URLが発行され、レスポンスのrel=previewであるatom:link要素のhref属性が共有URLとなります。指定を行わなかった場合、下書きプレビュー用の共有URLは発行されません。また、下書きではないエントリに対して"yes"を指定しても無効となります。
>https://developer.hatena.ne.jp/ja/documents/blog/apis/atom

**Comment by Songmu** [comment]
いいですね。
下書きにはyes指定をデフォルト指定にしてしまって、FrontmatterにPreviewURLみたいなのを書き加えても良いかもですね。

**Comment by Songmu** [comment]
v0.17.0 でリリースしました。contributionありがとうございました！
