### ISSUE TITLE
blogsync push stores the content to different filename than the original name

### ISSUE THREAD

**Issue by lufia** [x-motemen/blogsync#46]
I had a draft entry posted already to hatenablog CMS.  It was stored to **entry/2019/08/21/020240.md**, and it had *URL* entry header.

```console
$ sed -n '/---/,/---/p' entry/2019/08/21/020240.md
---
Title: title-title-title
Date: 2019-08-21T02:02:40+09:00
URL: https://example.org/entry/2019/08/21/020240
EditURL: https://blog.hatena.ne.jp/user/example.hateblo.jp/atom/entry/26006613401156491
Draft: true
---
```

Today, I updated the draft entry then pushed it. In that case **entry/2019/08/21/020240.md** is not modified. Instead `blogsync push` created a new file named **entry/2020/03/29/162048.md**.

```console
$ blogsync push entry/2019/08/21/020240.md 
       GET ---> https://blog.hatena.ne.jp/user/example.hateblo.jp/atom/entry/26006613401156491
       200 <--- https://blog.hatena.ne.jp/user/example.hateblo.jp/atom/entry/26006613401156491
       PUT ---> https://blog.hatena.ne.jp/user/example.hateblo.jp/atom/entry/26006613401156491
       200 <--- https://blog.hatena.ne.jp/user/example.hateblo.jp/atom/entry/26006613401156491
     store entry/2020/03/29/162048.md
```

Is this by design?

**Comment by Songmu** [comment]
これは、下書き時点のURLはテンポラリなURLで、実際のURLは公開時に決定されるという、はてなブログの仕様によるもので悩ましく思っています。せめて元のファイルを削除するような挙動になっていればよいのかも知れませんが…。

また、この現象を避けるために、明示的にエントリのURLを指定するcustom-pathを利用する方法も考えられます。

**Comment by lufia** [comment]
今の動作が仕様でないなら、pushするファイルのヘッダに

1. CustomPathがあればCustomPathを使う
2. URLがあればentry以下を維持する
3. Dateがあればentry/yyyy/mm/dd/hhmm00を使う(?)
4. どれもなければ今のまま

という動作にする案は、既存動作との互換性や使い勝手の文脈でどうでしょうか。問題なさそうならコード眺めてみます。

**Comment by Songmu** [comment]
CustomPathがあればCustomPathを使うのは良いと思っています。

ただ、URL自体は確かAtom API側が書き換えてしまうので維持するのはちょっとむずかしいと思います。

なので、下書き状態のやつは、 `entry/` 配下じゃなくて、 draft/{{entry_id}.md のようなところにpullしてくる(今回の場合 `draft/26006613401156491.md`)というのも考えられるかもしれません。(かなり大きな仕様変更にはなりますが…)

なんにせよ、下書き状態のやつをpublishした場合に、mdファイルの位置が変わったときに、元の下書き状態のファイルを消してしまうのはやってしまって良いとは思っています。

**Comment by lufia** [comment]
なるほど。ひとまず意図せず増え続けることがなければ良さそうなので削除できそうか眺めてみます。push元がdraftでなければ変わることはないと理解しました(たぶん)。

pushしたとき、
* draft → push → draft: ファイル名変わる
* draft → push → not draft: ファイル名変わる
* not draft → push → not draft: 変わらない

pullしたとき、
* TODO

CustomPathは、blogsync pullするとヘッダから消えてしまっているようにみえるので一旦忘れます。

**Comment by Songmu** [comment]
> push元がdraftでなければ変わることはない

はいそうです。

customPathは新規作成時には有効なのですがそれ以外のときはちょっとうまくいっていません…。多分API自体もその値を返すようになっていない気がします。

**Comment by Songmu** [comment]
これ、古い方のファイルがゴミにならないように消すようにしてみました。ご確認ください。

**Comment by lufia** [comment]
@Songmu ありがとうございます!
