### ISSUE TITLE
Missing fixed pages (固定ページ)

### ISSUE THREAD

**Issue by sudofox** [x-motemen/blogsync#60]
I created a test page here: https://sudofox.hatenablog.com/testpage

However, it isn't downloaded when I `blogsync pull sudofox.hatenablog.com`.

If this is not yet supported, please consider this as a feature request

**Comment by motemen** [comment]
Recently hatenablog added support for fixed pages, so it should be able to implement it!
[はてなブログAtomPub API に固定ページを操作する機能を追加しました - はてなブログ開発ブログ](https://staff.hatenablog.com/entry/2023/09/20/112358)

**Comment by sudofox** [comment]
hooray!
