### ISSUE TITLE
標準入力を経由せずに投稿する機能が欲しい

### ISSUE THREAD

**Issue by ongaeshi** [x-motemen/blogsync#61]
Windows だと標準入力を渡そうとしたときにエラーがでてしまいます。今はブラウザで空の記事を作成してから blogsync pull して回避しています。 

```
Error CreateFile /dev/stdin: The system cannot find the path specified.
```

標準入力を経由せずに投稿することはできるでしょうか？空の記事を作成したり内容を引数渡せたりするとありがたいです。

    blogsync post --draft --title=blogsync motemen.hatenablog.com  --content=さて何を書こうかな

**Comment by Songmu** [comment]
すみません、Windows環境には明るくないのですが、

`type path/to/file | blogsync post` や `echo 'さて何を書こうかな' | blogsync post` などでも無理でしょうか。

何れにせよ今の入力方法以外の方法を検討するのはやっても良いかも知れませんね。

**Comment by ongaeshi** [comment]
両方試してみましたが同じエラーになるようでした。

```
PS > type .\text.txt | blogsync post --draft --title=blogsync ongaeshi.hatenablog.com   
     error CreateFile /dev/stdin: The system cannot find the path specified.
PS > echo "draft" | blogsync post --draft --title=blogsync ongaeshi.hatenablog.com   
     error CreateFile /dev/stdin: The system cannot find the path specified.
```

今はほぼ下書きをはてなブログで直接作って、blogsync pull で取得、そのまま書いて blogsync push で投稿という運用をしています。とても便利です！ありがとうございます。

**Comment by ongaeshi** [comment]
WSL 版を使うことで標準入力が使えるようになりました。配布されているバージョンだと GLIB のバージョンなどで動かなかったため自前でビルドしたらうまくいきました。

https://ongaeshi.hatenablog.com/entry/2023/04/15/223505

※ ひとまず別の方法で解決したのでこの Issue は close します。
